---
title: "The complex network of trophic interactions in the Marine Protected Area Namuncurá-Banco Burdwood"
author: "Tomás I. Marina, Irene R. Schloss and Luciana Riccialdelli"
output: pdf_document
bibliography: "AMPBancoBurdwood.bib"
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

## Abstract

## Introduction

The objective of the present work was to build the network of predator-prey interactions (food web) for the Marine Protected Area Namuncurá - Banco Burdwood I (MPAN-BB), and characterize it in terms of complexity and structure.

## Methodology

### Study area

The MPAN-BB is a shallow submarine plateau called Burdwood Bank (BB) located 150 km east of Isla de los Estados and 200 km south from Malvinas/Falkland Islands (Figure 1). It comprises nearly 34.000 km^2 circumscribed by the 200 m isobath, between 54º–55ºS and 56º–62ºW, with a slight slope extended nearly 370 km east–west. The BB is surrounded by steep flanks of more than 3000 m depth through which strong currents circulate [@Piola1989; @Reta2014; @Matano2019]. Intense upwelling and mixing occur over it, entraining deep nutrient rich waters into the photic layer [@Piola2009; @Matano2019] and resulting in a fairly homogeneous water column both spatially and temporally [@Glorioso1995; @Guerrero1999; @Matano2019]. Physical features in the MPAN-BB are fairly stable, with salinity averaging 34 all year round and temperature ranging between 4 and 8 ºC overall [@Guerrero1999; @Acha2004; @Piola2009].

### Food web construction

### Food web analysis

We analyzed the MPA food web at 2 levels: 1) global, network-level properties (considers all species and interactions), and 2) species, species-level properties (considers the species’ role in the food web).
GLOBAL
Complexity: # trophic species, # interactions, link density, connectance
Degree distribution
Mean shortest path length
Omnivory
Distribution of prey and predator
Distribution of interactions by functional group

SPECIES
Centrality indices (betweenness, closeness)
Trophic similarity
Topological role

## Results

### Network-level properties

Most Functional groups show an asymmetric distribution of interactions: few species are relatively more connected than the rest.

Most consumers have a narrow potential diet, few have a broad diet.
Few prey are consumed by many predators, most prey have few predators.
Consumers w/ broad diet: Patagonotothen guntheri, P. ramsayi, Dissostichus eleginoides, Bathyraja brachyurops, B. griseocauda.
Prey w/ many predators: Detritus, Diatoms (benthic, centric, pennate), Euphausia spp., Foraminifera.

### Species-level properties

‘Network connector’ and ‘module connector’ species are responsible for linking modules and maintaining the connectivity of the food web. TL range for these species: 1 - 3.86.

Betweenness = Species at mid-trophic levels (3-4) present more shortest paths between species than any other species: ‘bridge’ role.
Closeness = Low-trophic level species are relatively closer to other species in the food web.

Trophic similarity: Species are more similar at mid-trophic levels (2-3) than in lower or higher ones. Basal and top species present a higher uniqueness in terms of trophic role.

## Discussion

The distribution of the interactions is asymmetric, where few species concentrate most of the interactions: Detritus, Diatoms (x3), Patagonotothen ramsayi & P. guntheri, Euphausia spp. The same happens within each functional group.

The most demanded food sources are: Detritus, Diatoms (x3), Euphausia spp., & Foraminifera.
Almost half of the consumers (47.64 %) are omnivores. Those with the broadest diets are: Patagonotothen ramsayi, P. guntheri, Dissostichus eleginoides, Bathyraja brachyurops, B. griseocauda.

Low and mid-trophic level species are responsible for maintaining the connectivity of the food web. The functional groups represented are: Amphipoda, Bivalvia, Bryozoa, Cnidaria, Cumacea, Decapoda, Detritus, Diatoms, Echinodermata, Fish (bentho-pelagic, demersal, chondrichthyes), Foraminifera, Polychaeta, Porifera, Zooplankton.

Low and mid-trophic level species present the highest betweenness and closeness values. These species have an important ‘bridge’ role and are close to other species.
Mid-trophic level species are more redundant than those at low and high trophic levels.

## References